### PR TITLE
Fix list updating inifite loading

### LINKED ISSUE #18: ublock update data bases broken. + no language selection.
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

When choose a data base, the plugin freeze, but does not update.
You can still click on a other setting, but it will not update the data bases.

Beside of that, why you cannot choose your own language, it's using my own language. But Prefer English.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
image

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Just choose a database, and apply/update

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Latest public Microsoft Edge Release
- uBlock Origin version: 1.9.11.101

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

### PR DESCRIPTION
**Pull request by japborst**
In some cases the updating of lists seemed to hang and spit out an `handle is invalid` error. For me, this revolved around the broadcast method that seemed to fail in some cases. From trial and error, I found that most cases it fails when a port has no `sender` object attached. This worked in most cases, but not all. 

Mozilla and MSDN have good docs on messaging, but as it works well in Chrome this seems to be Edge-specific (for which I couldn't find any docs).

Perhaps this is not the best solution, as we don't know the actual cause of the fail... But I'd like to argue to have this implement anyhow, as any weird error shouldn't stop the function from broadcasting the message.

Would fix #18. Both applying a new list selection and visually updating lists by showing the progress seem to work now.

### CODE REVIEW

File: platform/edge/vapi-background.js [hunk 1]
```diff
@@ -918,15 +918,20 @@ vAPI.messaging.setup = function(defaultHandler) {
 
 vAPI.messaging.broadcast = function(message) {
     var messageWrapper = {
-        broadcast: true,
-        msg: message
-    };
+            broadcast: true,
+            msg: message
+        };
```
Comment (nikrolls) [inline platform/edge/vapi-background.js]: Looks like an unintentional change here?

**Comment by nikrolls** [comment]
And sorry for the delay; GitHub notifications are still not being very helpful and alerting me when there is new activity.

**Comment by japborst** [comment]
@nikrolls Just updated. I subscribed to watch this repo and receive notifications for all issues and PRs through email, but I believe you can change that in your account settings.

**Comment by nikrolls** [comment]
Hmm, maybe I have some settings on my account causing an issue. I'll check it out.

**Comment by nikrolls** [comment]
Thanks for the contribution! I'll update the releases tonight and get this out with it.
